window_size: 5
train_start_date: 2022-11-13 13:30:00
train_end_date: 2023-01-01 9:30:00
valid_start_date: 2023-01-01 10:30:00
valid_end_date: 2023-02-16 10:30:00
features: Date, open, High, Low, close, volume #make sure to have Date High Low
indicators_names: rsi, macd


#short_wma, wma, long_wma, ewma, tema, macd, stoch1, stoch2, wpr, rsi_experts, rsi, srsi, bolinger_up,
#bolinger_down, kc_up, kc_down, tenkansen, kinjunsen, chikou, senkou_a, senkou_b, atr, momentum_,
#roc, vix, chop, cog

